# Generated by Django 5.2.6 on 2025-09-13 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('application_date', models.DateField(verbose_name='date applied')),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('interview', 'Interview Scheduled'), ('offer', 'Offer Received'), ('rejected', 'Rejected')], default='applied', max_length=50)),
            ],
        ),
    ]
