# Generated by Django 5.2.6 on 2025-09-13 19:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='application_date',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='date_applied',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(max_length=100),
        ),
    ]
