# Generated by Django 5.2.6 on 2025-09-13 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_remove_jobapplication_application_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='resumes/master/')),
            ],
        ),
    ]
