# Generated by Django 5.2.6 on 2025-09-13 20:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_masterresume'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='next_action',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='next_action_due',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='resume_variant',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('interviewing', 'Interviewing'), ('offered', 'Offer Received'), ('rejected', 'Rejected'), ('on_hold', 'On Hold')], default='applied', max_length=100),
        ),
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('call', 'Call'), ('portal', 'Portal'), ('meeting', 'Meeting'), ('other', 'Other')], default='email', max_length=20)),
                ('summary', models.TextField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comms', to='applications.jobapplication')),
            ],
        ),
    ]
