# Generated by Django 5.2.6 on 2025-09-13 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_masterresume'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='tailored_resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/tailored/'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('interviewing', 'Interviewing'), ('offered', 'Offer Received'), ('rejected', 'Rejected')], default='applied', max_length=100),
        ),
    ]
