# Generated by Django 5.2.6 on 2025-09-13 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_jobapplication_created_at_jobapplication_next_action_and_more'),
        ('applications', '0004_jobapplication_tailored_resume_and_more'),
    ]

    operations = [
    ]
